# Generated by Django 2.2.4 on 2019-08-27 17:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groomName', models.CharField(max_length=128, validators=[validators.validateChar])),
                ('brideName', models.CharField(max_length=128, validators=[validators.validateChar])),
                ('groomFamilyName', models.CharField(max_length=64, validators=[validators.validateChar])),
                ('brideFamilyName', models.CharField(max_length=64, validators=[validators.validateChar])),
                ('dateTime', models.DateTimeField()),
                ('venue', models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebpageVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.FileField(upload_to='webpages/videos/')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.Webpages')),
            ],
        ),
        migrations.CreateModel(
            name='WebpageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='webpages/images/')),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.Webpages')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('priority', models.PositiveSmallIntegerField()),
                ('done', models.BooleanField(default=False)),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.Webpages')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[validators.validateChar])),
                ('phone', models.CharField(max_length=10, validators=[validators.validateNo])),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.Webpages')),
            ],
        ),
    ]
