# Generated by Django 2.2.4 on 2019-08-28 15:57

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='note',
            field=models.CharField(max_length=64, validators=[validators.validateChar]),
        ),
    ]
