# Generated by Django 2.2.2 on 2019-08-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20190828_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.FileField(upload_to='webpages/static/fonts/')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.FileField(upload_to='webpages/static/themes/')),
            ],
        ),
        migrations.AddField(
            model_name='webpages',
            name='font',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.Fonts'),
        ),
        migrations.AddField(
            model_name='webpages',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.Themes'),
        ),
    ]
