# Generated by Django 2.0.6 on 2019-09-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20190829_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonts',
            name='fontName',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themes',
            name='themeName',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
