# Generated by Django 2.0.6 on 2019-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190827_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='uid',
            field=models.CharField(default=1, editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
