# Generated by Django 2.2.4 on 2019-08-28 14:59

from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=50, validators=[validators.validateUrl, validators.validateSite])),
                ('siteAddress', models.CharField(max_length=50, validators=[validators.validateUrl, validators.validateSite])),
                ('favIcon', models.ImageField(upload_to='settings/overview/')),
                ('googleAnalytic', models.CharField(max_length=50, validators=[validators.validateUrl, validators.validateSite])),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=50, null=True, validators=[validators.validateUrl, validators.validateSite])),
                ('instagram', models.CharField(max_length=50, null=True, validators=[validators.validateUrl, validators.validateSite])),
                ('tweeter', models.CharField(max_length=50, null=True, validators=[validators.validateUrl, validators.validateSite])),
                ('snapchat', models.CharField(max_length=50, null=True, validators=[validators.validateUrl, validators.validateSite])),
                ('pinterest', models.CharField(max_length=50, null=True, validators=[validators.validateUrl, validators.validateSite])),
            ],
        ),
    ]
