# Generated by Django 2.2.4 on 2019-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='googleAnalytic',
            field=models.CharField(max_length=128),
        ),
    ]
